DRIVER_PATH = r'/home/mango123/Downloads/chromedriver/chromedriver'
BANK_LINK = 'https://login.bankhapoalim.co.il/ng-portals/auth/en/'
BANK_USERNAME_SELECTOR = '#userCode'
BANK_PASSWORD_SELECTOR = '#password'
BANK_LOGIN_BTN_SELECTOR = 'body > auth-root > auth-rb-login > div > div.login-container > div.login-content > div > form > fieldset > div.login-submit > button'
BANK_BALANCE_SELECTOR = '#transactions-print-id-12-771-89610 > poalim-balance-and-limits > section > ul > li:nth-child(1) > div > span.currentBalance.d-inline-flex.number-positive'
BALANCE_PAGE_LINK = 'https://login.bankhapoalim.co.il/ng-portals/rb/en/current-account/transactions'
CONFIG_NAME = 'config.txt'
EMAIL='sanderslior@gmail.com'
DEFAULT_BALANCE=-1
MAIL_SERVER_EMAIL = 'smtp.gmail.com'
MAIL_SERVER_PORT = 465
HOUR = 60 * 60